Remove collections index - elastic indexer
multiversx/mx-chain-go pull request #4721
Opened 2022-11-21 11:47 UTC by miiu96

## Reasoning behind the pull request
- Upgrade elastic-indexer-go module. 
- Removed from `external.toml` file the `collections` index.

## Proposed changes
- Upgrade the `elastic-indexer-go` module with a version that will no longer index data in the `collections` index. 
- PR from elastic-indexer-go module: https://github.com/ElrondNetwork/elastic-indexer-go/pull/188

## Testing procedure
- Run a system test and check in the Elasticsearch databases that the collections index will no longer exist.

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/ElrondNetwork/elrond-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2022-11-21 11:49 UTC, iulianpascalau requested changes

2022-11-21 11:49 UTC, iulianpascalau commented on go.mod
> +	github.com/ElrondNetwork/elastic-indexer-go v1.2.44-0.20221121112957-7648441e8921
proper release

2022-11-22 11:35 UTC, gabi-vuls approved these changes
System test passed

2022-11-22 12:44 UTC, miiu96 commented on go.mod
> +	github.com/ElrondNetwork/elastic-indexer-go v1.2.44-0.20221121112957-7648441e8921
added

2022-11-23 07:14 UTC, iulianpascalau approved these changes

2023-03-08 07:38 UTC, closed without merging