dockerfile/termui: add Dockerfile for termui
multiversx/mx-chain-go pull request #4893
Opened 2023-01-20 16:53 UTC by Meria-finance

## Reasoning behind the pull request
- no docker image for termui is available
  
## Proposed changes
- adding Dockerfile for termui

## Testing procedure
- we've locally tested the docker image

2023-01-20 17:29 UTC, miiu96 approved these changes

2023-02-01 10:15 UTC, iulianpascalau commented on docker/termui/Dockerfile
> +RUN cp /go/pkg/mod/github.com/!elrond!network/arwen-wasm-vm@$(cat /go/mx-chain-go/go.mod | grep arwen-wasm-vm | sed 's/.* //' | tail -n 1)/wasmer/libwasmer_linux_amd64.so /lib/libwasmer_linux_amd64.s
I do not think we need the libwasmer_linux_amd64.so file management. So L7 & L11 can be removed

2023-02-01 10:31 UTC, iulianpascalau commented on docker/termui/Dockerfile
> +RUN cp /go/pkg/mod/github.com/!elrond!network/arwen-wasm-vm@$(cat /go/mx-chain-go/go.mod | grep arwen-wasm-vm | sed 's/.* //' | tail -n 1)/wasmer/libwasmer_linux_amd64.so /lib/libwasmer_linux_amd64.s
LE: no, it does not work without those lines, will refactor them when we will do the merge from `master` -> `rc/v1.4.0`

2023-02-01 10:33 UTC, iulianpascalau requested changes
commit is not verified. We will do the changes by our own. For future PRs please ensure that your commits are verified. Will close this PR.

2023-02-01 10:47 UTC, miiu96 commented
Hello 
We have created a new PR (https://github.com/multiversx/mx-chain-go/pull/4940)  for your request (we cannot merge this one because it has an unsigned commit). 
Thank you for this PR and for your contribution. 
This PR will be closed.

2023-02-01 10:47 UTC, closed without merging