upgrade indexer version
multiversx/mx-chain-go pull request #4956
Opened 2023-02-03 12:29 UTC by miiu96

## Reasoning behind the pull request
- Updated the version of the `mx-chain-es-indexer`
  
## Proposed changes
- The new version of the `mx-chain-es-indexer` will index extra fields in the Elasticsearch database
- PR from the `mx-chain-es`indexer`: https://github.com/multiversx/mx-chain-es-indexer-go/pull/201

## Testing procedure
- Fetch a transaction from the ES database it should have new fields like: `feeNum`, `valueNum` (for the normal transactions)
- Estd transactions should contain also the field `esdtValuesNum`

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2023-02-03 12:30 UTC, bogdan-rosianu requested changes

2023-02-03 12:30 UTC, bogdan-rosianu commented on go.mod
> +	github.com/multiversx/mx-chain-es-indexer-go v1.3.10-0.20230203121445-3b705455d196
proper tag before merging

2023-02-03 16:25 UTC, iulianpascalau reviewed
just the proper release

2023-02-06 12:07 UTC, iulianpascalau submitted a review, later dismissed

2023-02-06 12:13 UTC, iulianpascalau approved these changes

2023-02-06 12:14 UTC, bogdan-rosianu approved these changes

2023-02-06 13:39 UTC, gabi-vuls approved these changes
System test passed

2023-02-06 13:39 UTC, merged