FIX: Low waiting list edge case in StakingV4Step2
multiversx/mx-chain-go pull request #5111
Opened 2023-03-21 10:33 UTC by mariusmihaic

## Reasoning behind the pull request
- 
- 
- 
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2023-03-21 11:28 UTC, sasurobert approved these changes

2023-03-21 13:32 UTC, raduchis requested changes

2023-03-21 13:32 UTC, raduchis commented on sharding/nodesCoordinator/hashValidatorShuffler.go
> +		return false
some unitTest should have failed here. Can you please add an unit test?

2023-04-03 13:14 UTC, sasurobert approved these changes

2023-04-03 13:15 UTC, merged