Transfer ordering
multiversx/mx-chain-go pull request #5253
Opened 2023-05-19 07:35 UTC by matei-p

## Reasoning behind the pull request
- 
- 
- 
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2023-05-19 10:47 UTC, sasurobert requested changes

2023-05-19 10:47 UTC, sasurobert commented on process/smartContract/processorV2/processV2.go
> +		return false, []internalIndexedScr{{result, 0}}
we need real index - nextIndex here as well.

2023-05-19 10:47 UTC, sasurobert commented on process/smartContract/processorV2/vmOutputAccountsProcessor.go
> +func unwrapSCRs(indexedSCResults []internalIndexedScr) []data.TransactionHandler {
nice one :)

2023-05-24 09:40 UTC, sasurobert commented on vm/systemSmartContracts/eei.go
> +func (context *vmContext) NextOutputTransferIndex() uint32 {
move this function befor IsInterfaceNil

2023-05-24 09:40 UTC, sasurobert commented on vm/systemSmartContracts/eei.go
> +	context.crtTransferIndex++
set crtTransferIndex to 0 on CleanCache function.

2023-05-24 09:40 UTC, sasurobert commented on vm/systemSmartContracts/eei.go
> +func (context *vmContext) NextOutputTransferIndex() uint32 {
make if func (host *vmContext) to be inline with the whole file.

2023-05-25 09:07 UTC, sasurobert commented on vm/systemSmartContracts/eei.go
> +	context.crtTransferIndex++
This is not done.

2023-05-25 14:45 UTC, sasurobert approved these changes

2023-05-25 18:50 UTC, andrei-marinica approved these changes

2023-05-25 18:51 UTC, merged