Merge from log events
multiversx/mx-chain-go pull request #5396
Opened 2023-07-05 13:53 UTC by matei-p

## Reasoning behind the pull request
- 
- 
- 
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2023-07-11 10:42 UTC, iulianpascalau requested changes
please merge the original feat/ branch

2023-07-11 11:02 UTC, iulianpascalau approved these changes

2023-07-11 11:21 UTC, miiu96 commented
can you check the file `/node/external/logs/logsConverter.go` there you need to set the `AdditionalData`. You need also to extend the structure that is returned by the API.

2023-07-11 11:37 UTC, miiu96 requested changes
can you please check the `node/external/logs/logsConverter.go` there you need to set the `AdditionalData` field, and also extend the structure that is returned by the API

2023-07-11 13:56 UTC, sasurobert approved these changes

2023-07-11 14:55 UTC, iulianpascalau approved these changes

2023-07-12 06:37 UTC, miiu96 approved these changes

2023-07-12 07:53 UTC, merged