Sovereign accounts parser
multiversx/mx-chain-go pull request #5489
Opened 2023-08-16 16:43 UTC by mariusmihaic

## Reasoning behind the pull request
- 
- 
- 
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2023-08-22 12:53 UTC, sasurobert approved these changes

2023-08-23 15:29 UTC, raduchis requested changes

2023-08-24 07:54 UTC, mariusmihaic commented on genesis/parsing/errors.go
> +var errNilAccountsParser = errors.New("nil accounts parser provided")
Right, removed this one and used suggested one

2023-08-24 07:55 UTC, sasurobert approved these changes

2023-08-24 07:55 UTC, mariusmihaic commented on genesis/parsing/sovereignAccountsParser.go
> +	shardIDs[0] = core.SovereignChainShardId
Yes, it is the same, changed as suggested

2023-08-24 07:58 UTC, raduchis approved these changes

2023-08-24 07:58 UTC, raduchis commented on genesis/parsing/errors.go
> +var errNilAccountsParser = errors.New("nil accounts parser provided")
ok

2023-08-24 07:58 UTC, raduchis commented on genesis/parsing/sovereignAccountsParser.go
> +	shardIDs[0] = core.SovereignChainShardId
ok

2023-08-24 08:03 UTC, merged