Sovereign genesis meta block checker
multiversx/mx-chain-go pull request #5519
Opened 2023-08-23 13:05 UTC by mariusmihaic

## Reasoning behind the pull request
- 
- 
- 
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2023-08-25 14:12 UTC, raduchis requested changes

2023-08-28 09:45 UTC, mariusmihaic commented on cmd/sovereignnode/sovereignNodeRunner.go
> +		GenesisMetaBlockChecker:    processComp.NewDisabledGenesisMetaBlockChecker(),
That check is already being done in `setGenesisHeader`, before calling this func, so we only need it for meta. Will leave it as it is.

Although, thanks to your suggestion, I've decided to add extra check for disabled one(which I've renamed ti sovereign) to not contain meta block

2023-08-28 09:45 UTC, mariusmihaic commented on factory/processing/interface.go
> +	CheckGenesisMetaBlock(genesisBlocks map[uint32]data.HeaderHandler, validatorStatsRootHash []byte) error
Right, good point, changed it as suggested

2023-08-28 09:46 UTC, mariusmihaic commented on factory/processing/errors.go
> +var errGenesisMetaBlockDoesNotExist = errors.New("genesis meta block does not exist")
Moved errors as suggested

2023-08-28 13:16 UTC, raduchis commented on cmd/sovereignnode/sovereignNodeRunner.go
> +		GenesisMetaBlockChecker:    processComp.NewDisabledGenesisMetaBlockChecker(),
ok

2023-08-28 13:16 UTC, raduchis commented on factory/processing/errors.go
> +var errGenesisMetaBlockDoesNotExist = errors.New("genesis meta block does not exist")
ok

2023-08-28 13:16 UTC, raduchis approved these changes

2023-08-28 13:33 UTC, merged