apiResolverFactory refactor
multiversx/mx-chain-go pull request #5814
Opened 2024-01-08 15:50 UTC by axenteoctavian

## Reasoning behind the pull request
- MX-14961 task
- 
- 
  
## Proposed changes
- refactor function createScQueryElement
- 
- 

## Testing procedure
- running sovereign node
- running main node
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2024-01-11 17:47 UTC, mariusmihaic requested changes

2024-01-11 17:47 UTC, mariusmihaic commented on factory/api/apiResolverFactory.go
> +		err = addSystemVMToContainer(args, vmContainer, argsHook)
Inside this if you need to to actually do `argsHook.Accounts = accAdapter`

2024-01-11 17:49 UTC, mariusmihaic commented on factory/api/apiResolverFactory.go
> +	argsHook.BlockChain = apiBlockchain
Actually, for our use case, you only need to pass arround `accAdapter` pointer.
apiBlockChain creation should remain specific for each func inside of them

2024-01-15 10:46 UTC, sasurobert submitted a review, later dismissed

2024-01-15 12:46 UTC, mariusmihaic commented on factory/api/apiResolverFactory.go
> +	var accAdapter state.AccountsAdapterAPI
I think these declarations can be removed.
We only need below to assign in `argsHook` the correct pointers

2024-01-15 12:46 UTC, mariusmihaic commented on factory/api/apiResolverFactory_test.go
> +	t.Run("regular chain should NOT add systemVM", func(t *testing.T) {
This is a good test for regular shard chain. We should also check the factory for a metachain shard chain in an unit test, if it doesn't already exist

2024-01-15 14:59 UTC, mariusmihaic commented on factory/api/apiResolverFactory_test.go
>  	t.Run("regular chain should NOT add systemVM", func(t *testing.T) {
```suggestion
	t.Run("regular chain for shards should only add wasm vm", func(t *testing.T) {
```

2024-01-15 14:59 UTC, mariusmihaic commented on factory/api/apiResolverFactory_test.go
> +	t.Run("metachain chain should NOT add systemVM", func(t *testing.T) {
```suggestion
	t.Run("regular chain for meta should only add systemVM", func(t *testing.T) {
```

2024-01-16 09:25 UTC, mariusmihaic approved these changes

2024-01-23 12:43 UTC, sasurobert approved these changes

2024-01-23 14:28 UTC, merged