initSystemAccount new function
multiversx/mx-chain-go pull request #5815
Opened 2024-01-08 16:14 UTC by axenteoctavian

## Reasoning behind the pull request
- MX-14968 task
- 
- 
  
## Proposed changes
- init system account function add
- 
- 

## Testing procedure
- running sovereign node
-
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2024-01-09 14:50 UTC, mariusmihaic requested changes

2024-01-09 14:50 UTC, mariusmihaic commented on genesis/process/sovereignGenesisBlockCreator.go
> +	err = gbc.initSystemAccount()
Please add unit test

2024-01-11 11:21 UTC, sasurobert submitted a review, later dismissed

2024-01-11 15:58 UTC, mariusmihaic commented on genesis/process/sovereignGenesisBlockCreator_test.go
> +		SaveAccountCalled: func(account vmcommon.AccountHandler) error {
We should also check that the saved account address is for system account first time.
We can add this check:

```go
			if !saveAccountWasCalled {
				require.Equal(t, core.SystemAccountAddress, account.AddressBytes())
			}

```

2024-01-11 16:10 UTC, mariusmihaic approved these changes

2024-01-15 10:33 UTC, mariusmihaic approved these changes

2024-01-15 10:47 UTC, sasurobert approved these changes

2024-01-15 11:57 UTC, merged