config param update
multiversx/mx-chain-go pull request #5828
Opened 2024-01-11 12:34 UTC by axenteoctavian

## Reasoning behind the pull request
- MX-14985 task
- 
- 
  
## Proposed changes
- set IsPayableBySCEnableEpoch = 0
- 
- 

## Testing procedure
- running sovereign node
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2024-01-15 10:44 UTC, sasurobert submitted a review, later dismissed

2024-01-15 12:23 UTC, mariusmihaic requested changes

2024-01-15 12:23 UTC, mariusmihaic commented on cmd/sovereignnode/config/enableEpochs.toml
> +    IsPayableBySCEnableEpoch = 0
This is not enough.

We need more changes in this PR:
- cmd/node/config/config.toml (we will discuss how to address this changes)
- Add these changes:
```
  updateTOMLValue enableEpochs.toml "SCDeployEnableEpoch" 0
  updateTOMLValue enableEpochs.toml "BuiltInFunctionsEnableEpoch" 0
  updateTOMLValue enableEpochs.toml "ESDTEnableEpoch" 0
```
- Update go mods for es indexer from this PR: https://github.com/multiversx/mx-chain-go/pull/5635

2024-01-16 09:43 UTC, mariusmihaic requested changes
This config will not start without vm = 1.5.

1. Please create the task we discussed about with over writable configs from prefs.toml for structs.
2. In  `cmd/node/config/config.toml`, for both `WasmVMVersions` entries, use only one entry with this value: `{ StartEpoch = 0, Version = "v1.5" },`. Also, for both entries, add a TODO with the task id to refactor it with over writable configs once the above mentioned task is completed

2024-01-30 13:15 UTC, mariusmihaic approved these changes

2024-01-30 14:31 UTC, merged