Refactor chainRunType references
multiversx/mx-chain-go pull request #5883
Opened 2024-01-29 08:38 UTC by axenteoctavian

## Reasoning behind the pull request
- 
- 
- 
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2024-02-12 11:52 UTC, mariusmihaic requested changes
This is wrong.
1. Do not create a PR which includes another merges/prs
2. Split refactor into multiple, smaller, targeted prs

2024-02-19 10:10 UTC, mariusmihaic requested changes

2024-02-19 10:10 UTC, mariusmihaic commented on factory/vm/sovereignVmContainerShardCreator.go
> +	blockChainHookImpl, err := svcsf.blockChainHookHandlerCreator.CreateBlockChainHookHandler(argsHook)
Actually, sovereign container should hold internally both shard+meta creators(from constructor, as pointers)
Inside this func it should call:
1. shard.Create...
2. meta.Create...

2024-02-19 10:10 UTC, mariusmihaic commented on factory/vm/sovereignVmContainerShardCreator.go
> +	argsHook.MissingTrieNodesNotifier = syncer.NewMissingTrieNodesNotifier()
You should not create new pointers, but used the same ones as in other components.
Anyway, this should probably be removed after the refactor above is done

2024-02-19 10:10 UTC, mariusmihaic commented on factory/vm/sovereignVmContainerShardCreator.go
> +	}, nil
Check nil and return error

2024-02-19 10:10 UTC, mariusmihaic commented on factory/vm/sovereignVmContainerShardCreator_test.go
> +func TestNewSovereignVmContainerShardCreatorFactory(t *testing.T) {
Also add test for nil input pointer

2024-02-19 10:10 UTC, mariusmihaic commented on factory/vm/vmContainerMetaCreator.go
> +	}, nil
Check nil + return error

2024-02-19 10:10 UTC, mariusmihaic commented on factory/vm/vmContainerMetaCreator_test.go
> +func TestNewVmContainerMetaCreatorFactory(t *testing.T) {
Also test for nil here

2024-02-19 10:10 UTC, mariusmihaic commented on factory/vm/vmContainerShardCreator.go
> +	}, nil
Check nil + return error

2024-02-19 10:10 UTC, mariusmihaic commented on factory/vm/vmContainerShardCreator_test.go
> +func TestNewVmContainerShardCreatorFactory(t *testing.T) {
Also test here

2024-02-19 10:10 UTC, mariusmihaic commented on factory/vm/vmContainerShardCreator_test.go
> +			{StartEpoch: 10, Version: "v1.2"},
Do you really need all of these?

2024-02-19 11:17 UTC, axenteoctavian commented on factory/api/apiResolverFactory_test.go
> +	t.Run("NewFeeComputer fails should error", func(t *testing.T) {
First, the name `NewTransactionCostEstimator` might be very old.
In Radu's PR this function was like [this](https://github.com/multiversx/mx-chain-go/blob/7d8df22022526e394a8c8cac828106afef155bf6/factory/api/apiResolverFactory.go#L207) , so `failingStepsInstance.enableEpochsHandlerFailingStep` is correct. But right now the only parameter is `EconomicsData` so I had to change

2024-02-19 15:38 UTC, axenteoctavian commented on factory/processing/blockProcessorCreator.go
> +	counter, err := counters.NewUsageCounter(esdtTransferParser)
This counter is for `VmContainerCreator factory`.
I refactored the `createVMFactoryShard` and `createVMFactoryMeta` and used the factory instead (this was for other file)

2024-02-20 07:38 UTC, sasurobert commented on factory/api/apiResolverFactory.go
> +	factoryVm "github.com/multiversx/mx-chain-go/factory/vm"
goimports

2024-02-20 07:38 UTC, sasurobert commented on factory/vm/vmContainerMetaCreator_test.go
> +	"github.com/multiversx/mx-chain-go/process"
goimports

2024-02-20 07:38 UTC, sasurobert commented on factory/vm/vmContainerShardCreator_test.go
> +	"github.com/multiversx/mx-chain-go/process"
goimports

2024-02-20 07:38 UTC, sasurobert commented on testscommon/factory/vmContainerMetaFactoryMock.go
> +type VMContainerMetaFactoryMock struct {
comments on public functions

2024-02-20 07:38 UTC, sasurobert commented on testscommon/factory/vmContainerShardFactoryMock.go
> +type VMContainerShardFactoryMock struct {
comments on public functions

2024-02-20 08:39 UTC, mariusmihaic commented on factory/vm/sovereignVmContainerShardCreator.go
> +func NewSovereignVmContainerShardFactory(bhhc hooks.BlockChainHookHandlerCreator, vcm VmContainerCreator, vcs VmContainerCreator) (*sovereignVmContainerShardFactory, error) {
Can we please use full name/detailed naming for vcm/vcs variables?

2024-02-20 08:39 UTC, mariusmihaic commented on factory/vm/sovereignVmContainerShardCreator_test.go
> +		sovereignVmContainerShardFactory, err := vm.NewSovereignVmContainerShardFactory(nil, nil, nil)
Please use nil only for first argument(blockchainHool) and mocks/components for the rest

2024-02-20 08:39 UTC, mariusmihaic commented on factory/vm/sovereignVmContainerShardCreator.go
> +	if bhhc == nil {
Please use check.IfNil for all checks.
Applies for all files

2024-02-20 09:28 UTC, mariusmihaic approved these changes

2024-02-20 09:56 UTC, sasurobert approved these changes

2024-02-20 09:57 UTC, merged