miniblocks transactions fixes and unit tests
multiversx/mx-chain-go pull request #5921
Opened 2024-02-06 13:31 UTC by axenteoctavian

## Reasoning behind the pull request
- Correction for transactions that should be added in the scheduled mini block
- 
- 
  
## Proposed changes
- `isTransactionEligibleForExecution` function should return the error
error => is not added in the miniblock and for some cases removed from txpool (e.g. InsufficientFee, LowerNonce)
no error => is added in the miniblock (including txs with InsufficientFunds)

## Testing procedure
- running sovereign node and sending bad transactions
- a full testing plan with transaction should be defined later
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2024-02-06 13:43 UTC, axenteoctavian commented on process/block/preprocess/sovereignChainTransactions.go
`computeSortedTxs` function is not sorting transactions by move balance as for mainnet. Is this needed for sovereign?

2024-02-06 13:51 UTC, sasurobert approved these changes

2024-02-06 13:51 UTC, sasurobert commented on process/block/preprocess/sovereignChainTransactions.go
> +		// do not return error here because you want this tx to be added in the miniblock and executed as INVALID
good find

2024-02-07 08:06 UTC, sasurobert submitted a review, later dismissed

2024-02-07 09:14 UTC, AdoAdoAdo requested changes

2024-02-07 09:14 UTC, AdoAdoAdo commented on process/block/preprocess/transactionsV2.go
>  		if isTxTargetedForDeletion {
this condition should only be used for removing transactions from txpool.

2024-02-07 09:23 UTC, axenteoctavian commented on process/block/preprocess/transactionsV2.go
> +		isTxTargetedForDeletion := errors.Is(executionErr, process.ErrLowerNonceInTransaction) || errors.Is(executionErr, process.ErrHigherNonceInTransaction) || errors.Is(executionErr, process.ErrInsuffic
right!

2024-02-07 12:30 UTC, AdoAdoAdo approved these changes

2024-02-07 13:23 UTC, merged