Fixed the p2p configs
multiversx/mx-chain-go pull request #5947
Opened 2024-02-12 11:05 UTC by iulianpascalau

## Reasoning behind the pull request
- fixed the p2p configs
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2024-02-12 11:11 UTC, sstanculeanu approved these changes

2024-02-12 11:13 UTC, sstanculeanu requested changes
same issue on fullArchiveP2P.toml and seed node p2p.toml

2024-02-12 12:46 UTC, sstanculeanu approved these changes

2024-02-12 12:56 UTC, AdoAdoAdo approved these changes

2024-02-13 16:53 UTC, gabi-vuls approved these changes
Normal allin test: v1.6.15-dev-config-eb2e06c06d -> fix-p2p-configs-143e5d619f

--- Specific errors ---

block hash does not match 222
wrong nonce in block 205
miniblocks does not match 0
num miniblocks does not match 0
miniblock hash does not match 0
block bodies does not match 0
receipts hash missmatch 0

/------/


--- Statistics ---

Nr. of all ERRORS:  0
Nr. of all WARNS:  217
Nr. of new ERRORS:  0
Nr. of new WARNS:  0
Nr. of PANICS:  0

/------/

--- ERRORS ---

/------/

--- WARNINGS ---

/------/

2024-02-13 17:07 UTC, merged