proper flag for GovernanceFlagInSpecificEpochOnly
multiversx/mx-chain-go pull request #5975
Opened 2024-02-17 12:39 UTC by raduchis

## Reasoning behind the pull request
- 
- 
- 
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2024-02-17 12:47 UTC, iulianpascalau approved these changes

2024-02-17 12:48 UTC, schimih submitted a review, later dismissed

2024-02-17 13:45 UTC, sstanculeanu submitted a review, later dismissed

2024-02-18 10:48 UTC, sstanculeanu commented on epochStart/metachain/systemSCs.go
> +		common.GovernanceFlagInSpecificEpochOnly,
Reverted the actual fix

2024-02-19 08:50 UTC, iulianpascalau requested changes
where is the flag fix?

2024-02-19 08:56 UTC, iulianpascalau approved these changes

2024-02-19 08:57 UTC, sstanculeanu approved these changes

2024-02-19 09:50 UTC, schimih approved these changes

2024-02-19 09:59 UTC, merged