Genesis epoch
multiversx/mx-chain-go pull request #5986
Opened 2024-02-21 11:49 UTC by miiu96

## Reasoning behind the pull request
- Added an option to set the genesis epoch
  
## Proposed changes
- Extended the `config.toml` file with the GenesisEpoch paramter

## Testing procedure
- Ensure the internal testnet is working properly.

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2024-02-21 12:14 UTC, iulianpascalau submitted a review, later dismissed

2024-02-21 12:14 UTC, iulianpascalau commented on cmd/node/config/config.toml
> +    GenesisEpoch = 0
:+1:

2024-02-21 12:14 UTC, iulianpascalau commented on node/chainSimulator/configs/configs.go
> +	configs.EpochConfig.EnableEpochs.StakingV2EnableEpoch = args.InitialEpoch + 1
We might add a TODO to fix the staking v2

2024-02-21 15:29 UTC, iulianpascalau requested changes

2024-02-21 15:42 UTC, miiu96 commented on genesis/process/genesisBlockCreator.go
> +var genesisNonce uint64
fixed

2024-02-21 15:42 UTC, iulianpascalau approved these changes

2024-02-22 08:29 UTC, sstanculeanu approved these changes

2024-02-23 12:17 UTC, gabi-vuls approved these changes
Normal allin test: v1.6.15-dev-config-eb2e06c06d -> configurable-epoch-a31eafa7fd

--- Specific errors ---

block hash does not match 157
wrong nonce in block 144
miniblocks does not match 0
num miniblocks does not match 0
miniblock hash does not match 0
block bodies does not match 0
receipts hash missmatch 0

/------/


--- Statistics ---

Nr. of all ERRORS:  0
Nr. of all WARNS:  233
Nr. of new ERRORS:  0
Nr. of new WARNS:  1
Nr. of PANICS:  0

/------/

--- ERRORS ---

/------/

--- WARNINGS ---

up-mad-validator-27 :
Warn: trie recreate error:           error = getNodeFromDB error: key not found for key root =  1

/------/

2024-02-23 12:58 UTC, merged