outgoing operations in runType components
multiversx/mx-chain-go pull request #6066
Opened 2024-03-26 13:14 UTC by axenteoctavian

## Reasoning behind the pull request
- 
- 
- 
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2024-04-09 13:06 UTC, mariusmihaic commented on factory/runType/runTypeComponents.go
> +	outGoingOperationsPool := disabled.NewDisabledOutGoingOperationPool()
You can add it directly in returned obj

2024-04-09 13:06 UTC, mariusmihaic commented on factory/runType/sovereignRunTypeComponents.go
> +	outGoingOperationsPoolCreator := sovereignFactory.NewOutGoingOperationPool(expiryTime)
This is not a creator, it is the outgoing op pool
```suggestion
	outGoingOperationsPool:= sovereignFactory.NewOutGoingOperationPool(expiryTime)
```

2024-04-09 13:06 UTC, mariusmihaic commented on process/block/baseProcess_test.go
> +				args.RunTypeComponents = &mock.RunTypeComponentsStub{AccountCreator: &stateMock.AccountsFactoryStub{}, OutGoingOperationsPool: nil}
Same remark as in previous PR

2024-04-09 13:06 UTC, mariusmihaic commented on process/block/interface.go
> -type OutGoingOperationsPool interface {
It was better to keep the interface definition at user/caller side, not where the implementation of the interface is.
Can stay as it is, though....

2024-04-09 13:06 UTC, mariusmihaic commented on process/mock/runTypeComponentsStub.go
> +func (r *RunTypeComponentsStub) OutGoingOperationsPoolHandler() sovereignBlock.OutGoingOperationsPool {
Add missing comm

2024-04-09 14:49 UTC, axenteoctavian commented on consensus/spos/bls/sovereignSubRoundEnd.go
> +	sovereignBlock "github.com/multiversx/mx-chain-go/dataRetriever/dataPool/sovereign"
I created an interface

2024-04-15 09:00 UTC, mariusmihaic commented on factory/runType/sovereignRunTypeComponents.go
> +	outGoingOperationsPool := sovereignFactory.NewOutGoingOperationPool(expiryTime)
Put directly in return

2024-04-15 11:15 UTC, raduchis approved these changes

2024-04-16 09:20 UTC, mariusmihaic requested changes

2024-04-16 09:20 UTC, mariusmihaic commented on process/mock/runTypeComponentsStub.go
> +// DataDecoderHandler -
```suggestion
// DataCodecHandler -
```

2024-04-16 13:06 UTC, raduchis submitted a review, later dismissed

2024-04-16 13:34 UTC, mariusmihaic submitted a review, later dismissed

2024-04-16 13:34 UTC, mariusmihaic approved these changes

2024-04-16 13:37 UTC, raduchis approved these changes

2024-04-16 13:46 UTC, merged