refactor shard coordinator factory
multiversx/mx-chain-go pull request #6077
Opened 2024-03-29 08:14 UTC by axenteoctavian

## Reasoning behind the pull request
- Refactor `ShardCoordinatorFactory`
- 
- 
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2024-04-11 07:31 UTC, axenteoctavian commented on integrationTests/testInitializer.go
> +	runTypeComponents := mainFactoryMocks.NewRunTypeComponentsStub()
I deleted this because RunTypeComponents already comes from arguments and this was not even used

2024-04-11 07:32 UTC, axenteoctavian commented on testscommon/components/components.go
> +func GetSovereignCoreComponents() factory.CoreComponentsHolder {
Yes, will refactor `componens.go` at the end

2024-04-11 07:32 UTC, axenteoctavian commented on testscommon/components/components.go
> +func GetSovereignProcessArgs(
Yes, will refactor `componens.go` at the end

2024-04-11 07:32 UTC, axenteoctavian commented on testscommon/components/components.go
> +func GetSovereignDataComponents(coreComponents factory.CoreComponentsHolder, shardCoordinator sharding.Coordinator) factory.DataComponentsHolder {
Yes, will refactor `componens.go` at the end

2024-04-15 09:08 UTC, mariusmihaic requested changes

2024-04-15 09:08 UTC, mariusmihaic commented on factory/bootstrap/bootstrapComponents_test.go
> +func getRunTypeComponentsMock() *mainFactoryMocks.RunTypeComponentsStub {
Same remark, this is NOT OK.

2024-04-15 11:37 UTC, raduchis approved these changes

2024-04-16 09:21 UTC, mariusmihaic approved these changes

2024-04-16 13:47 UTC, mariusmihaic approved these changes

2024-04-16 14:01 UTC, merged