fix backwards compatibility issues in legacySystemSCs
multiversx/mx-chain-go pull request #6105
Opened 2024-04-04 12:45 UTC by AdoAdoAdo

## Reasoning behind the pull request
- 
- 
- 
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2024-04-08 13:46 UTC, sasurobert approved these changes

2024-04-08 13:49 UTC, sasurobert approved these changes

2024-04-09 08:24 UTC, sasurobert requested changes

2024-04-09 08:24 UTC, sasurobert commented on epochStart/metachain/legacySystemSCs.go
> +	err = s.replaceValidators(jailedValidator, newValidatorInfo, validatorsInfoMap)
I have to agree here. let's do the code without returning error. and the same with unStakeNodesWithNotEnoughFunds - if we cannot replace - we keep that old validator and it should be good.

2024-04-09 09:21 UTC, AdoAdoAdo commented on epochStart/metachain/legacySystemSCs.go
> +	err = s.replaceValidators(jailedValidator, newValidatorInfo, validatorsInfoMap)
Yes, as mentioned when opening the PR, I wanted to discuss the errors that have been added here by @mariusmihaic. My preference was also to not change the initial behavior (in regards to the new errors being returned). 

The code here was to have something to start the discussion and see that the backwards issue is solved.

Will remove the errors for v4 as well.

2024-04-10 11:14 UTC, AdoAdoAdo commented on state/interface.go
> +	DeleteKey(blsKey []byte, shardID uint32)
done

2024-04-10 11:32 UTC, AdoAdoAdo commented on epochStart/metachain/legacySystemSCs.go
> +	_ = validatorsInfoMap.ReplaceValidatorByKey(old.GetPublicKey(), new, old.GetShardId())
added a log

2024-04-10 11:36 UTC, iulianpascalau approved these changes

2024-04-10 11:37 UTC, sasurobert approved these changes

2024-04-10 12:09 UTC, mariusmihaic approved these changes

2024-04-10 13:44 UTC, merged