Chain simulator updates for sovereign
multiversx/mx-chain-go pull request #6150
Opened 2024-05-09 07:58 UTC by axenteoctavian

## Reasoning behind the pull request
- 
- 
- 
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2024-05-10 09:03 UTC, mariusmihaic requested changes

2024-05-10 09:03 UTC, mariusmihaic commented on node/chainSimulator/chainSimulator.go
> +		if idx == -1 {
Please revert this

2024-05-10 11:39 UTC, mariusmihaic approved these changes

2024-05-13 10:00 UTC, mariusmihaic requested changes

2024-05-13 10:00 UTC, mariusmihaic commented on node/chainSimulator/chainSimulator_test.go
> +			// (the owner is not set at genesis anymore because we do not enable the staking v2 in that phase)
This test should pass regardless of this. Something is wrong if this fails without this enable epoch.

2024-05-13 12:11 UTC, mariusmihaic approved these changes

2024-05-13 12:46 UTC, miiu96 approved these changes

2024-05-14 10:21 UTC, gabi-vuls approved these changes

2024-05-14 10:33 UTC, merged