FIX: ProcessBuiltIn + SetBurnRole
multiversx/mx-chain-go pull request #6157
Opened 2024-05-13 08:42 UTC by mariusmihaic

## Reasoning behind the pull request
- 
- 
- 
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2024-05-14 06:47 UTC, sasurobert requested changes

2024-05-14 06:47 UTC, sasurobert commented on vm/systemSmartContracts/sovereignEEI.go
> +func (sovHost *sovereignVMContext) SendGlobalSettingToAll(sender []byte, input []byte) error {
There is no need for this. Please revert. like really really no need.

2024-05-14 06:47 UTC, sasurobert commented on vm/systemSmartContracts/sovereignEEI.go
> +func (sovHost *sovereignVMContext) SendGlobalSettingToAll(sender []byte, input []byte) error {
remove the context handler.

2024-05-14 07:27 UTC, sasurobert commented on vm/systemSmartContracts/sovereignEEI.go
> +func NewSovereignVMContext(vmContext vm.ContextHandler) (*sovereignVMContext, error) {
This is NewSystemVMEEI - SovereignVMContext sounds bad.

It is ok that you pushed this context handler, but it needs a new name. It is the execution environmnent interface for the SystemVM.

2024-05-14 10:22 UTC, sasurobert commented on vm/systemSmartContracts/eei.go
> +	if host.isSovereignSCToSCCall(input) {
isInShardSCToSCCall is a better name.

2024-05-14 10:28 UTC, mariusmihaic commented on vm/systemSmartContracts/eei.go
> +	if host.isSovereignSCToSCCall(input) {
Right, fixed it

2024-05-15 08:43 UTC, sasurobert commented on vm/systemSmartContracts/systemVMEEI.go
> +func NewSystemVMEEI(vmContext vm.ContextHandler) (*systemVMEEI, error) {
This should be NewOneShardSystemVMEEI, the name is not good.

And should also have a rework on ProcessBuiltInFunction as well, without the sameShard IF in that case.

2024-05-15 09:40 UTC, axenteoctavian approved these changes

2024-05-15 09:42 UTC, sasurobert approved these changes

2024-05-15 09:42 UTC, sasurobert commented on vm/systemSmartContracts/oneShardSystemVMEEI.go
> +	// TODO: MX-15470 remove sameShard check from ProcessBuiltInFunction
actually have your own definition of ProcessBuiltInFunction - do not touch the ProcessBuiltInFunction from the original EEI.

2024-05-15 09:50 UTC, merged