disable relayed v3
multiversx/mx-chain-go pull request #6563
Opened 2024-10-25 08:50 UTC by sstanculeanu

## Reasoning behind the pull request
- 
- 
- 
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2024-10-31 08:40 UTC, elvisboghiu commented
System tests result:

Normal allin test: 1.8.2-0ef7d5d1d5 -> relayedv3_deactivation-0aba9812d6

--- Specific errors --- 

block hash does not match 1670
wrong nonce in block 874
miniblocks does not match 0
num miniblocks does not match 0
miniblock hash does not match 0
block bodies does not match 0
receipts hash missmatch 0

/------/ 

--- Statistics --- 

Nr. of all ERRORS:  1
Nr. of all WARNS:  373
Nr. of new ERRORS:  1
Nr. of new WARNS:  30
Nr. of PANICS:  0

/------/ 

--- System test go --- 

All scenarios from system-test-go are OK!
/------/ 

--- ERRORS ---  

do-ams-observer-4 : 
Error: context deadline exceeded while closing the http server in gin/webServer  1

/------/ 

--- WARNINGS ---  

do-ams-validator-3 : 
Warn: shardProcessor.createMiniBlocks     error = shard is stuck shard =  1

do-ams-validator-19 : 
Warn: shardProcessor.createMiniBlocks     error = shard is stuck shard =  1

do-ams-validator-1 : 
Warn: shardProcessor.createMiniBlocks     error = shard is stuck shard =  1

do-ams-validator-29 : 
Warn: shardProcessor.createMiniBlocks     error = shard is stuck shard =  1

do-ams-validator-35 : 
Warn: shardProcessor.createMiniBlocks     error = shard is stuck shard =  1

do-ams-validator-4 : 
Warn: shardProcessor.createMiniBlocks     error = shard is stuck shard =  1

do-ams-validator-26 : 
Warn: shardProcessor.createMiniBlocks     error = shard is stuck shard =  3

do-ams-validator-9 : 
Warn: shardProcessor.createMiniBlocks     error = shard is stuck shard =  1

do-ams-validator-20 : 
Warn: shardProcessor.createMiniBlocks     error = shard is stuck shard =  1

do-ams-validator-13 : 
Warn: shardProcessor.createMiniBlocks     error = shard is stuck shard =  2

do-ams-validator-27 : 
Warn: basePreProcess.saveTransactionToStorage txHash = dataUnit = TransactionUnit error = missing transaction  8
Warn: basePreProcess.createMarshalledData: tx not found hash =  8
Warn: shardProcessor.createMiniBlocks     error = shard is stuck shard =  1

/------/

2024-10-31 09:19 UTC, elvisboghiu approved these changes

2024-10-31 12:40 UTC, raduchis approved these changes

2024-10-31 12:41 UTC, raduchis requested changes
do not merge this

2024-11-14 07:45 UTC, sstanculeanu commented
Closing the PR, not needed anymore, devnet upgraded to a newer version.

2024-11-14 07:45 UTC, closed without merging