Don't notify cache about nonces; provide the account nonce provider, instead
multiversx/mx-chain-go pull request #6603
Opened 2024-11-13 21:13 UTC by andreibancioiu

## Reasoning behind the pull request
- 
- 
- 
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2024-11-14 12:49 UTC, sasurobert submitted a review, later dismissed

2024-11-14 18:48 UTC, raduchis approved these changes

2024-11-19 12:35 UTC, andreibancioiu commented on state/accountsDB.go
> +	log.Trace("accountsDB.GetExistingAccount", "address", address)
Optimizations.

2024-11-19 12:38 UTC, andreibancioiu commented on node/external/transactionAPI/apiTransactionProcessor.go
> +		if len(guardedTx.GetGuardianAddr()) > 0 {
This is from https://github.com/multiversx/mx-chain-go/pull/6604.

2024-11-19 12:40 UTC, andreibancioiu commented on integrationTests/multiShard/relayedTx/relayedTx_test.go
> +		roundToPropagateMultiShard := int64(40)
Test was extremely hard to debug.

It seems that it was affected by the new behavior of the cache, that does not return transactions with lower nonces during selection.

2024-11-19 12:49 UTC, andreibancioiu commented on dataRetriever/requestHandlers/requestHandler.go
> +	epoch := rrh.getEpoch()
CC: @sstanculeanu

2024-11-21 08:13 UTC, andreibancioiu commented on genesis/process/shardGenesisBlockCreator.go
> +		disabledGuardian.NewDisabledGuardedAccountHandler(),
Genesis components, we can pass this object.

2024-11-21 08:16 UTC, andreibancioiu commented on process/block/preprocess/miniBlockBuilder.go
> -func (mbb *miniBlocksBuilder) updateAccountShardsInfo(tx *transaction.Transaction, wtx *txcache.WrappedTransaction) {
Was used for mempool notifications.

2024-11-21 09:06 UTC, andreibancioiu commented on process/constants.go
> +const TxCacheSelectionLoopMaximumDuration = 250 * time.Millisecond
Question for review: all right?

2024-11-26 17:02 UTC, raduchis requested changes

2024-11-26 19:28 UTC, andreibancioiu commented on go.mod
> +	github.com/multiversx/mx-chain-storage-go v1.0.18-0.20241124203643-93c958ad66cf
Will be set after all merges into the feat branch, right before preparing the release.

2024-11-26 19:49 UTC, andreibancioiu commented on process/block/preprocess/basePreProcess.go
> +	accountStateProvider       *accountStateProvider
It's already handled a bit differently in the next PR:

https://github.com/multiversx/mx-chain-go/pull/6628/files#diff-acfb4fa3ec74315de16957c120913b7150aaeb7ccd1374dc1b12ce0c4a4d8048R1414

2024-11-26 19:55 UTC, andreibancioiu commented on process/block/preprocess/transactions.go
>  const selectionGasBandwidthIncreaseScheduledPercent = 130
Changed :+1:

2024-11-27 14:07 UTC, andreibancioiu commented on process/block/preprocess/transactions.go
> +const selectionGasBandwidthIncreasePercent = 400
We should, yes. Added MX-16201 (we have some other constants to move to config).

2024-11-27 14:08 UTC, andreibancioiu commented on go.mod
> +	github.com/multiversx/mx-chain-storage-go v1.0.18-0.20241126200205-8a0cb502901f
We reference the latest commit from here: https://github.com/multiversx/mx-chain-storage-go/pull/57/commits.

A proper tag be set after all merges into the feat branch, right before preparing the release.

2024-11-27 15:15 UTC, raduchis commented on dataRetriever/txpool/memorytests/memory_test.go
> +	journals = append(journals, runScenario(t, newScenario(10000, 1, 1024, "0"), memoryAssertion{10, 16}, memoryAssertion{0, 10}))
ok!

2024-11-27 15:16 UTC, raduchis commented on process/block/preprocess/transactions.go
>  const selectionGasBandwidthIncreaseScheduledPercent = 130
ok!

2024-11-27 15:16 UTC, raduchis commented on process/block/preprocess/basePreProcess.go
> +	accountStateProvider       *accountStateProvider
ok

2024-11-27 15:17 UTC, raduchis approved these changes

2024-11-27 16:22 UTC, AdoAdoAdo approved these changes

2024-11-27 16:32 UTC, sasurobert approved these changes

2024-11-27 17:15 UTC, merged